server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/intellihire
    username: ishan
    password: Ishan123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  devtools:
    restart:
      enabled: true

jwt:
  secret: myverysecureandlongsecretkey1234567890
  expiration: 86400000 # 24 hours

logging:
  level:
    org.springframework: INFO

cors:
  allowed-origins: "http://localhost:3000"